
FROM node:18

WORKDIR /usr/src/app

# Copy package.json and install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the client code
COPY . .

# Expose port for the frontend (adjust if you're using a different port)
EXPOSE 5173

# Command to run the frontend
CMD ["npm", "run", "dev"]
