version: '3'
services:
  backend:
    build: ./api
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb+srv://khruthwik:khruthwik@khruthwik.m0mu0l8.mongodb.net/my-database?retryWrites=true&w=majority
    volumes:
      - ./api:/usr/src/app

  frontend:
    build: ./client
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    volumes:
      - ./client:/usr/src/app
